FROM ev:01

# copying docker backend and frontend
COPY ./scripts/stages.py /utils/
COPY ./scripts/main_ui.py /utils/
COPY ./scripts/main_batch.py /utils/
COPY ./entrypoint.sh /utils/
# running service entrypoint
RUN chmod +x /utils/entrypoint.sh
CMD ["/utils/entrypoint.sh"]
