FROM ev:01

RUN sudo apt install libtiff5 -y

# Config files
COPY ./config/complex_config.txt /home/utils/
COPY ./config/monomer_config_all.txt /home/utils/

# copying docker backend and frontend
COPY ./scripts/main_ui.py /home/utils/
RUN chmod +rwx /home/utils/main_ui.py
COPY ./scripts/main_batch.py /home/utils/
RUN chmod +rwx /home/utils/main_batch.py
COPY ./scripts/stages.py /home/utils/
RUN chmod +rwx /home/utils/stages.py
COPY ./entrypoint.sh /home/utils/
RUN chmod +x /home/utils/entrypoint.sh
# running service entrypoint
CMD ["/home/utils/entrypoint.sh"]
