version: "3.9"
services:
  app:
    build: .
    image: ev:01
    volumes:
      - ${USER_INPUT:-~/Desktop/data}:/evcomplex/
    environment:
      - USER_INPUT
    stdin_open: true
    tty: true
    command: --rm

  # docker-compose run -e path/to/input #--rm app

