name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - setuptools=68.0.0
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - numba=0.57.1
  - ruamel.yaml=0.17.35
  - matplotlib=3.7.2
  - requests=2.31.0
  - mmtf-python=1.1.3
  - click=8.0.4
  - filelock=3.9.0
  - psutil=5.9.0
  - bokeh=3.2.1
  - jinja2=3.1.2
  - biopython=1.81
  - seaborn=0.12.2
  - billiard=4.1.0
  - scikit-learn=1.3.0
  - sqlite=3.41.2
